"""Generated protobuf + gRPC stubs for the Custos sidecar .

Generated by ``grpc_tools.protoc`` from ``src/custos/sidecar/custos_v1.proto``.
The single top-level ``import custos_v1_pb2`` in the generated
``custos_v1_pb2_grpc.py`` was rewritten to a fully-qualified relative
import so the modules load under ``custos.sidecar.proto.*`` without
requiring ``custos_v1_pb2`` on ``sys.path`` independently.

Regenerate with::

    python -m grpc_tools.protoc \\
        -I src/custos/sidecar \\
        --python_out=src/custos/sidecar/proto \\
        --grpc_python_out=src/custos/sidecar/proto \\
        src/custos/sidecar/custos_v1.proto

then re-apply the single-line fix in ``custos_v1_pb2_grpc.py``::

    -import custos_v1_pb2 as custos__v1__pb2
    +from custos.sidecar.proto import custos_v1_pb2 as custos__v1__pb2

mypy excludes the proto package (see ``pyproject.toml [tool.mypy]``);
the re-exports below are typed as ``Any`` because the protobuf-generated
symbols are dynamic at static-analysis time.

The schema imports `google.protobuf.Struct`; importing `struct_pb2`
here pre-registers its descriptor so the generated `_pb2.py` finds
``google/protobuf/struct.proto`` in the descriptor pool.
"""

from google.protobuf import struct_pb2  # noqa: F401 - registers the descriptor

from custos.sidecar.proto.custos_v1_pb2 import (  # noqa: F401
    AuditEvent,
    DecideRequest,
    DecideResponse,
    Decision,
    Invocation,
    SubjectContext,
    ToolDescriptor,
)
from custos.sidecar.proto.custos_v1_pb2_grpc import (  # noqa: F401
    CustosGatewayServicer,
    CustosGatewayStub,
    add_CustosGatewayServicer_to_server,
)

__all__ = [
    "AuditEvent",
    "DecideRequest",
    "DecideResponse",
    "Decision",
    "Invocation",
    "SubjectContext",
    "ToolDescriptor",
    "CustosGatewayServicer",
    "CustosGatewayStub",
    "add_CustosGatewayServicer_to_server",
]
